# Generated by Django 3.2.7 on 2021-09-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='Posted_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
