# Generated by Django 3.2.7 on 2021-09-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_notice_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='Text',
            field=models.CharField(max_length=1000),
        ),
    ]
