# Generated by Django 3.2.7 on 2021-09-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_branch_students_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='students',
            name='contact',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AddField(
            model_name='students',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
