# Generated by Django 3.2.7 on 2021-09-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210916_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='poll_ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.students')),
            ],
        ),
        migrations.CreateModel(
            name='poll_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.poll_ques')),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.students')),
            ],
        ),
    ]
