# Generated by Django 3.2.7 on 2021-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='text',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
