# Generated by Django 3.2.7 on 2021-09-18 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_tasks_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 18)),
            preserve_default=False,
        ),
    ]
