# Generated by Django 3.2.7 on 2021-09-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_tasks_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='Posted_by',
        ),
    ]
