# Generated by Django 3.2.7 on 2021-09-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_remove_notice_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='Posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.students'),
        ),
    ]
